version: '2'

services:
  shinyproxy:
    image: jiewpeng/shinyproxy:1.0.0
    network_mode: host
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
