shiny:
  proxy:
    title: Open Analytics Shiny Proxy
    logo-url: http://www.openanalytics.eu/sites/www.openanalytics.eu/themes/oa/logo.png
    landing-page: /
    heartbeat-rate: 10000
    heartbeat-timeout: 60000
    port: 8080
    authentication: ldap
    admin-groups: scientists
    # Example: 'ldap' authentication configuration
    ldap:
      url: ldap://localhost:389/dc=example,dc=org
      user-dn-pattern: uid={0},ou=Users
      group-search-base: ou=Groups
      group-search-filter: (uniqueMember={0})
      manager-dn: cn=readonly,dc=example,dc=org
      manager-password: readonly
    # Docker configuration
    docker:
      cert-path: /home/none
      url: http://localhost:2375
      port-range-start: 20000
  apps:
  - name: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    docker-cmd: ["R", "-e shinyproxy::run_01_hello()"]
    docker-image: openanalytics/shinyproxy-demo
    groups: scientists, mathematicians, scientists1
  - name: 06_tabsets
    docker-cmd: ["R", "-e shinyproxy::run_06_tabsets()"]
    docker-image: openanalytics/shinyproxy-demo
    groups: scientists
  - name: simpleapp
    display-name: Simple App
    description: displays the session info and logged in user
    docker-cmd: ["R", "-e", "shiny::runApp('/root/simpleapp')"]
    docker-image: jiewpeng/r-simpleapp
    groups: scientists, mathematicians

logging:
  file:
    shinyproxy.log
